<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Detail_dosen_model extends CI_Model
{

    public $table = 'detail_dosen';
    public $id = 'id_detail_dosen';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_detail_dosen,tbl_dosen.id_dosen,tbl_dosen.nama_dosen,tbl_jabatan.id_jabatan,tbl_jabatan.jabatan');
        $this->datatables->from('detail_dosen');
        //add this line for join
        $this->datatables->join('tbl_dosen', 'detail_dosen.id_dosen = tbl_dosen.id_dosen');
        $this->datatables->join('tbl_jabatan', 'detail_dosen.id_jabatan = tbl_jabatan.id_jabatan');
        $this->datatables->add_column('action', anchor(site_url('detail_dosen/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('detail_dosen/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('detail_dosen/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_detail_dosen');
        return $this->datatables->generate();
    }
    function trx_detail_dosen($id)
    {
        $this->db->select('id_detail_dosen,tbl_dosen.id_dosen,tbl_dosen.nama_dosen,tbl_jabatan.id_jabatan,tbl_jabatan.jabatan');
        $this->db->from('detail_dosen');
        $this->db->join('tbl_dosen', 'detail_dosen.id_dosen = tbl_dosen.id_dosen');
        $this->db->join('tbl_jabatan', 'detail_dosen.id_jabatan = tbl_jabatan.id_jabatan');
        $this->db->where($this->id, $id);
        $query = $this->db->get()->row();
        return $query;
    }
    function cari_dosenprodi($prodi)
    {
        $this->db->select('id_detail_dosen,tbl_dosen.id_dosen,tbl_dosen.nama_dosen,tbl_jabatan.id_jabatan,tbl_jabatan.jabatan');
        $this->db->from('detail_dosen');
        $this->db->join('tbl_dosen', 'detail_dosen.id_dosen = tbl_dosen.id_dosen');
        $this->db->join('tbl_jabatan', 'detail_dosen.id_jabatan = tbl_jabatan.id_jabatan');
        $this->db->like('tbl_jabatan.jabatan', "Ketua Program Studi ".$prodi."");
        $query = $this->db->get()->result();
        return $query;
    }
    function trx_pembimbing()
    {
        $this->db->select('id_detail_dosen,tbl_dosen.id_dosen,tbl_dosen.nama_dosen as "dosen",tbl_jabatan.id_jabatan,tbl_jabatan.jabatan');
        //$this->db->from('detail_dosen');
        $this->db->join('tbl_dosen', 'detail_dosen.id_dosen = tbl_dosen.id_dosen');
        $this->db->join('tbl_jabatan', 'detail_dosen.id_jabatan = tbl_jabatan.id_jabatan');
        // $this->db->where($this->id, $id_dosen);
        $this->db->where('detail_dosen.id_jabatan', '7')->or_where('detail_dosen.id_jabatan', '8');
        return $this->db->get('detail_dosen');
        //return $query;
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_detail_dosen', $q);
	$this->db->or_like('id_dosen', $q);
	$this->db->or_like('id_jabatan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_detail_dosen', $q);
	$this->db->or_like('id_dosen', $q);
	$this->db->or_like('id_jabatan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Detail_dosen_model.php */
/* Location: ./application/models/Detail_dosen_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-08-31 05:16:08 */
/* http://harviacode.com */