<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Prodi_model extends CI_Model
{

    public $table = 'tbl_prodi';
    public $id = 'id_prodi';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('tbl_prodi.id_prodi,tbl_prodi.kode_prodi,tbl_jenjangstudi.kode_studi,tbl_prodi.nama_prodi');
        $this->datatables->from('tbl_prodi');
        //add this line for join
        $this->datatables->join('tbl_jenjangstudi', 'tbl_prodi.id_jenjangstudi = tbl_jenjangstudi.id_jenjangstudi');
        $this->datatables->add_column('action', anchor(site_url('prodi/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('prodi/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('prodi/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_prodi');
        return $this->datatables->generate();
    }
    function trx_prodi($id)
    {
        $this->db->select('tbl_prodi.id_prodi,tbl_prodi.kode_prodi,tbl_jenjangstudi.kode_studi,tbl_prodi.nama_prodi');
        $this->db->from('tbl_prodi');
        //add this line for join
        $this->db->join('tbl_jenjangstudi', 'tbl_prodi.id_jenjangstudi = tbl_jenjangstudi.id_jenjangstudi');
        $this->db->where($this->id, $id);
        $query = $this->db->get()->row();
        return $query;
    }
    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_prodi', $q);
	$this->db->or_like('kode_prodi', $q);
	$this->db->or_like('nama_prodi', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_prodi', $q);
	$this->db->or_like('kode_prodi', $q);
	$this->db->or_like('nama_prodi', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Prodi_model.php */
/* Location: ./application/models/Prodi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-08-31 05:21:15 */
/* http://harviacode.com */